# Generated by Django 5.2.14 on 2026-05-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fretes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='fretes.frete')),
            ],
        ),
    ]
