# Generated by Django 5.2.14 on 2026-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=160)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('origem', models.CharField(max_length=160)),
                ('destino', models.CharField(max_length=160)),
                ('carga', models.CharField(max_length=160)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cubagem_m3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aprovada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
