# Generated by Django 5.2.14 on 2026-05-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fretes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=20)),
                ('descricao', models.CharField(max_length=180)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('frete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fretes.frete')),
            ],
        ),
    ]
