# Generated by Django 5.2.14 on 2026-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('antt', models.CharField(blank=True, max_length=30)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('veiculo', models.CharField(blank=True, max_length=80)),
                ('carroceria', models.CharField(blank=True, max_length=80)),
                ('aprovado_risco', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
