# Generated by Django 5.2.14 on 2026-05-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motoristas', '0001_initial'),
        ('transportadoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=160)),
                ('destino', models.CharField(max_length=160)),
                ('carga', models.CharField(max_length=160)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cubagem_m3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_motorista', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_pagamento', models.CharField(blank=True, max_length=120)),
                ('data_coleta', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PROSPECTANDO', 'Prospectando'), ('AGENDADO', 'Agendado'), ('EM_TRANSITO', 'Em trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motoristas.motorista')),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportadoras.transportadora')),
            ],
        ),
    ]
